# Generated by Django 2.2 on 2020-02-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Notes',
            new_name='notes',
        ),
    ]
